method: grid
metric:
  goal: maximize
  name: eval_score


parameters:
  lr:
    values: [7.0e-4]
  random_seed:
    values: [3, 4, 5, 6, 7]
  buffer_size:
    values: [100]
  num_env_mean_calculation:
    values: [10]
  shift_level:
    values: [0.5, 0.8, 1.2, 2.0, 5.0]
  env:
    values: ["hopper_gravity", "walker2d_gravity", "halfcheetah_gravity", "hopper_friction", "walker2d_friction", "halfcheetah_friction"]
  max_step:
    values: [1000000]
  algorithm:
    values: ["low_fidelity_only_baseline_reinforce"]